### ISSUE TITLE
Doesn't seem to work on the Canadian Uber Eats

### ISSUE THREAD

**Issue by GabrielSerealia** [pxue/better-eats#1]
When I use the script on the Canadian Uber Eats https://www.ubereats.com/ca/feed
It doesn't seem to filter out non BOGO offers or hide blacklisted restaurants
The script has a little red icon on TamperMonkey indicating the script it loaded
And it shows the injected fields to configure the script settings on the page
But if I click any uber eats filters or apply the Better Eats filter it hides the script entirely and doesn't show anything filtered out
Is there anything I could do to assist if you need any troubleshooting

**Comment by pxue** [comment]
@GabrielSerealia hey for now the script only works on the pre-filtered "Offers" page
make sure you have that option checked off.

<img width="317" alt="Screenshot 2023-10-05 at 11 01 07 PM" src="https://github.com/pxue/better-eats/assets/270494/e2797c6a-a715-40bd-834e-851bc3693a7a">

and reload the page until you see the extra filters on the right side of the screen.
