### ISSUE TITLE
UberEats updated his interface and now is broken :(

### ISSUE THREAD

**Issue by japo89** [pxue/better-eats#2]
Hi!

I think there is a bug because UberEats updates today his interface.. could you fix it? thankss!

![7b597ffba77b4c673053edab490f187d](https://github.com/pxue/better-eats/assets/116621105/edf370a4-b580-4e59-b620-708e9c038701)

**Comment by pxue** [comment]
hey @japo89 reinstall the script, I just pushed an update.

**Comment by japo89** [comment]
> hey @japo89 reinstall the script, I just pushed an update.

Uhm I don't know if is my problem, but I don't have any update, only from 12 december and I have it installed. How can I update? I reinstalled anyway but it doesn't work. Thanks for your effort!

**Comment by pxue** [comment]
@japo89 oh wow not just you. I guess Ubereats were rolling out the web changes over time, I just got it.

I'll take a look! thanks for reporting.

**Comment by japo89** [comment]
Hii! Any news about the fix? The extension helped too much 😥 thankss!

**Comment by pxue** [comment]
@japo89 finally updated the changes. sorry for taking so long :)
