### ISSUE TITLE
 UberEats updated again

### ISSUE THREAD

**Issue by dexteon** [pxue/better-eats#3]
Hey it looks like UberEats updated again and broke it, any advice on how we can modify it to make it work?

**Comment by alexricher** [comment]
Hi! I think I'm experiencing the same on my end. I've tried it today, but it doesn't seem like it does anything on UberEats (Canadian version) using Brave and with developer mode enabled.

Is the script officially outdated?

Thanks nonetheless for sharing it! 👍

**Comment by pxue** [comment]
Hey try now. Gave it bunch of updates.
